[package]
name = "brak_adnotacji_typow"
version = "0.1.0"
authors = ["Twoje imiÄ™ i nazwisko <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
